######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 10 09:16:21 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += simpleqt4.cpp
